### PR TITLE
response.url from Location header

### LINKED ISSUE #6: solidResonse.url should always have full IRI
if someone needs just the paths or relative IRI, helper methods can provide it based on full IRI but not the other way!

### PR DESCRIPTION
**Pull request by elf-pavlik**
fixes #6

### CODE REVIEW

**Comment by elf-pavlik** [comment]
does it also solve #1 which I might duplicated in #6 ?

i could add a commit to change .location to .url in https://github.com/solid/solid-web-client/blob/6d582c556b0576ccd2b0a39ae8dad19ea4ae58cb/src/client.js#L81

**Comment by dmitrizagidulin** [comment]
👍 , thanks @elf-pavlik.

(Yeah, if you don't mind, can you fix the .location reference & change it to .url, like you mentioned).

**Comment by dmitrizagidulin** [comment]
And yes, this also solves #1

**Comment by elf-pavlik** [comment]
done!

i didn't write test for that since i don't understand why you need to pass response.url while you already pass response and  .url from it will anyways overwrite passed url, so in this case you could pass `null` or whatever since it doesn't matter ... but we can discuss it sometimes later on the chat

https://github.com/solid/solid-web-client/blob/6d582c556b0576ccd2b0a39ae8dad19ea4ae58cb/src/models/resource.js#L47-L53

**Comment by dmitrizagidulin** [comment]
Thanks! Merging.

**Pull request merged**
